// This model was generated by Forest CLI. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/reference-guide/models/enrich-your-models
module.exports = (sequelize, DataTypes) => {
  const { Sequelize } = sequelize;
  // This section contains the fields of your model, mapped to your table's columns.
  // Learn more here: https://docs.forestadmin.com/documentation/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
  const CoachSkill = sequelize.define('coachSkill', {
    skillLevel: {
      type: DataTypes.INTEGER,
      allowNull: false,
    },
    createdAt: {
      type: DataTypes.DATE,
      defaultValue: Sequelize.literal('now()'),
    },
    updatedAt: {
      type: DataTypes.DATE,
      defaultValue: Sequelize.literal('now()'),
    },
  }, {
    tableName: 'coach_skill',
    underscored: true,
    schema: process.env.DATABASE_SCHEMA,
  });

  // This section contains the relationships for this model. See: https://docs.forestadmin.com/documentation/reference-guide/relationships#adding-relationships.
  CoachSkill.associate = (models) => {
    CoachSkill.belongsTo(models.coach, {
      foreignKey: {
        name: 'coachIdKey',
        field: 'coach_id',
      },
      as: 'coach',
    });
    CoachSkill.belongsTo(models.sessionType, {
      foreignKey: {
        name: 'sessionTypeIdKey',
        field: 'session_type_id',
      },
      as: 'sessionType',
    });
  };

  return CoachSkill;
};
