// This model was generated by Forest CLI. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/reference-guide/models/enrich-your-models
module.exports = (sequelize, DataTypes) => {
  const { Sequelize } = sequelize;
  // This section contains the fields of your model, mapped to your table's columns.
  // Learn more here: https://docs.forestadmin.com/documentation/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
  const SessionCourse = sequelize.define('sessionCourse', {
    startTime: {
      type: DataTypes.DATE,
      allowNull: false,
    },
    endTime: {
      type: DataTypes.DATE,
      allowNull: false,
    },
    createdAt: {
      type: DataTypes.DATE,
      defaultValue: Sequelize.literal('now()'),
    },
    updatedAt: {
      type: DataTypes.DATE,
      defaultValue: Sequelize.literal('now()'),
    },
  }, {
    tableName: 'session_course',
    underscored: true,
    schema: process.env.DATABASE_SCHEMA,
  });

  // This section contains the relationships for this model. See: https://docs.forestadmin.com/documentation/reference-guide/relationships#adding-relationships.
  SessionCourse.associate = (models) => {
    SessionCourse.belongsTo(models.session, {
      foreignKey: {
        name: 'sessionIdKey',
        field: 'session_id',
      },
      as: 'session',
    });
    SessionCourse.hasMany(models.attendance, {
      foreignKey: {
        name: 'sessionCourseIdKey',
        field: 'session_course_id',
      },
      as: 'sessionCourseAttendances',
    });
  };

  return SessionCourse;
};
